baseURL: 'https://adamdingman.net'
languageCode: en-us
title: Adam Dingman - Cloud, DevOps, IoT
theme: PaperMod
description: Technology consultant curious about all things Cloud, DevOps and IoT
params:
    label:
      text: Adam Dingman
    defaultTheme: light
    disableThemeToggle: true
    profileMode:
        enabled: true
        author: Adam Dingman
        title: Adam Dingman
        subtitle: Cloud, DevOps, IoT
        imageUrl: /images/profile-photo.jpg
        imageWidth: 300
        imageHeight: 300
    socialIcons:
      - name: "twitter"
        url: "https://twitter.com/adam_dingman"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/adamdingman/"     
      - name: "email"
        url: "mailto:adam@adamdingman.net"
    hideFooter: true
    env: production
    images:
    - /images/profile-photo.jpg
    # cover:
    #   hidden: false # hide everywhere but not in structured data
    #   hiddenInList: false # hide on list pages and home
    #   hiddenInSingle: false # hide on single page
menu:
  main:
    - identifier: About
      name: About
      url: "/about"
      weight: 10
    - identifier: Certifications
      name: Certifications
      url: "/certifications"
      weight: 10
    - identifier: Blog
      name: Blog
      url: "/posts"
      weight: 10
googleAnalytics: G-WGJK2RQ8MH 
