baseURL: 'https://apdingman.github.io'
languageCode: en-us
title: Adam Dingman
theme: PaperMod
params:
    defaultTheme: light
    disableThemeToggle: true
    profileMode:
        enabled: true
        Title: Adam Dingman
        Content: Father to 2 boys and 1 girl
        imageUrl: /images/profile-photo.jpg
        buttons:
          - name: Blog
            url: "/posts"
    socialIcons:
      - name: "twitter"
        url: "https://twitter.com/adam_dingman"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/adamdingman/"     
      - name: "email"
        url: "mailto:adam@adamdingman.net"
    hideFooter: true   
    images:
    - /images/profile-photo.jpg
    # cover:
    #   hidden: false # hide everywhere but not in structured data
    #   hiddenInList: false # hide on list pages and home
    #   hiddenInSingle: false # hide on single page
menu:
  main:
    - identifier: About
      name: About
      url: "/about"
      weight: 10
    - identifier: Certifications
      name: Certifications
      url: "/certifications"
      weight: 10
    - identifier: Blog
      name: Blog
      url: "/posts"
      weight: 10
    - identifier: My Favorite Tweets
      name: My Favorite Tweets
      url: "/tweets/my-fav-tweets"
      weight: 10
googleAnalytics: G-WGJK2RQ8MH 
